# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.19.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.19.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/rajmishra/Documents/cpp/cann

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/rajmishra/Documents/cpp/cann

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.19.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.19.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/rajmishra/Documents/cpp/cann/CMakeFiles /Users/rajmishra/Documents/cpp/cann//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/rajmishra/Documents/cpp/cann/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cann

# Build rule for target.
cann: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cann
.PHONY : cann

# fast build rule for target.
cann/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cann.dir/build.make CMakeFiles/cann.dir/build
.PHONY : cann/fast

src/Layer.o: src/Layer.cc.o

.PHONY : src/Layer.o

# target to build an object file
src/Layer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cann.dir/build.make CMakeFiles/cann.dir/src/Layer.cc.o
.PHONY : src/Layer.cc.o

src/Layer.i: src/Layer.cc.i

.PHONY : src/Layer.i

# target to preprocess a source file
src/Layer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cann.dir/build.make CMakeFiles/cann.dir/src/Layer.cc.i
.PHONY : src/Layer.cc.i

src/Layer.s: src/Layer.cc.s

.PHONY : src/Layer.s

# target to generate assembly for a file
src/Layer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cann.dir/build.make CMakeFiles/cann.dir/src/Layer.cc.s
.PHONY : src/Layer.cc.s

src/NeuralNetwork.o: src/NeuralNetwork.cc.o

.PHONY : src/NeuralNetwork.o

# target to build an object file
src/NeuralNetwork.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cann.dir/build.make CMakeFiles/cann.dir/src/NeuralNetwork.cc.o
.PHONY : src/NeuralNetwork.cc.o

src/NeuralNetwork.i: src/NeuralNetwork.cc.i

.PHONY : src/NeuralNetwork.i

# target to preprocess a source file
src/NeuralNetwork.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cann.dir/build.make CMakeFiles/cann.dir/src/NeuralNetwork.cc.i
.PHONY : src/NeuralNetwork.cc.i

src/NeuralNetwork.s: src/NeuralNetwork.cc.s

.PHONY : src/NeuralNetwork.s

# target to generate assembly for a file
src/NeuralNetwork.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cann.dir/build.make CMakeFiles/cann.dir/src/NeuralNetwork.cc.s
.PHONY : src/NeuralNetwork.cc.s

src/Neuron.o: src/Neuron.cc.o

.PHONY : src/Neuron.o

# target to build an object file
src/Neuron.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cann.dir/build.make CMakeFiles/cann.dir/src/Neuron.cc.o
.PHONY : src/Neuron.cc.o

src/Neuron.i: src/Neuron.cc.i

.PHONY : src/Neuron.i

# target to preprocess a source file
src/Neuron.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cann.dir/build.make CMakeFiles/cann.dir/src/Neuron.cc.i
.PHONY : src/Neuron.cc.i

src/Neuron.s: src/Neuron.cc.s

.PHONY : src/Neuron.s

# target to generate assembly for a file
src/Neuron.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cann.dir/build.make CMakeFiles/cann.dir/src/Neuron.cc.s
.PHONY : src/Neuron.cc.s

src/main.o: src/main.cc.o

.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cann.dir/build.make CMakeFiles/cann.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cann.dir/build.make CMakeFiles/cann.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cann.dir/build.make CMakeFiles/cann.dir/src/main.cc.s
.PHONY : src/main.cc.s

src/matrix.o: src/matrix.cc.o

.PHONY : src/matrix.o

# target to build an object file
src/matrix.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cann.dir/build.make CMakeFiles/cann.dir/src/matrix.cc.o
.PHONY : src/matrix.cc.o

src/matrix.i: src/matrix.cc.i

.PHONY : src/matrix.i

# target to preprocess a source file
src/matrix.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cann.dir/build.make CMakeFiles/cann.dir/src/matrix.cc.i
.PHONY : src/matrix.cc.i

src/matrix.s: src/matrix.cc.s

.PHONY : src/matrix.s

# target to generate assembly for a file
src/matrix.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cann.dir/build.make CMakeFiles/cann.dir/src/matrix.cc.s
.PHONY : src/matrix.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cann"
	@echo "... src/Layer.o"
	@echo "... src/Layer.i"
	@echo "... src/Layer.s"
	@echo "... src/NeuralNetwork.o"
	@echo "... src/NeuralNetwork.i"
	@echo "... src/NeuralNetwork.s"
	@echo "... src/Neuron.o"
	@echo "... src/Neuron.i"
	@echo "... src/Neuron.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/matrix.o"
	@echo "... src/matrix.i"
	@echo "... src/matrix.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

